### ISSUE TITLE
Bug after updating to 2.5.0

### ISSUE THREAD

**Issue by imikim** [timholy/Revise.jl#410]
(compiled mode) evaluation error starting at /Users/imran/.julia/packages/Revise/S7mrl/src/Revise.jl:97
  invalid redefinition of constant queue_errors

This happens right in the beginning

**Comment by imikim** [comment]
Sorry, not sure what caused it, but now it has disappeared - I had already tried stopping and restarting julia - I did it another time and it's fine now

**Comment by imikim** [comment]
Sorry, not sure what caused it, but now it has disappeared - I had already tried stopping and restarting julia - I did it another time and it's fine now

**Comment by timholy** [comment]
That looks consistent with Revise updating itself in a running session from an older version. That indeed should be a one-time error message.
