### ISSUE TITLE
Wrong "Invalid redefinition of type"  for certain `UnionAll` field types

### ISSUE THREAD

**Issue by stev47** [timholy/Revise.jl#770]
Minimal example:
```julia
using Revise

mktemp() do f, io
    write(io, """
        struct A{T} end
        struct B{T, S}
          a::A{<:T}
        end
        """)
    close(io)
    includet(f)
end
```
results in
```
ERROR: LoadError: invalid redefinition of type B
```
The above works (try in fresh session) if either:
  - `A{<:T}` is replaced with `A{T}`,
  - `S` is removed, or
  - `includet` replaced by standard `include`

This breaks normal `Revise` workflow *even if no types are changed* at all.
#734 possibly related.

**Comment by aviatesk** [comment]
The above example seems to work on the latest master and v1.10-beta3 with Revise v3.5.7. What is your Julia version and Revise version?

**Comment by stev47** [comment]
> The above example seems to work on the latest master and v1.10-beta3 with Revise v3.5.7. What is your Julia version and Revise version?

```
julia> versioninfo()
Julia Version 1.9.3
Commit bed2cd540a1 (2023-08-24 14:43 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 16 × AMD Ryzen 7 5825U with Radeon Graphics
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, znver3)
  Threads: 1 on 16 virtual cores
Environment:
  JULIA_PKG_USE_CLI_GIT = 1

(@v1.9) pkg> status Revise
Status `~/.julia/environments/v1.9/Project.toml`
  [295af30f] Revise v3.5.7
```
I did not try yet on v1.10 or master

**Comment by stev47** [comment]
> The above example seems to work on the latest master and v1.10-beta3 with Revise v3.5.7. What is your Julia version and Revise version?

I managed to reproduce both on Julia `1.10.0-beta3` and current master (`1.11.0-DEV.745`), each with `Revise v3.5.7`.

**Comment by thofma** [comment]
Might be a dup of #753?

**Comment by timholy** [comment]
Thanks for the MWE!

Bad news: this may be a Julia bug. (Revise just exploits the standard Julia functionality here.) `includet` effectively re-evaluates the file, skipping over anything that it think it can omit. You can mimic this by calling `include` twice on the same file:
```julia
# don't load Revise
julia> mktemp() do f, io
           write(io, """
               struct A{T} end
               struct B{T, S}
                 a::A{<:T}
               end
               """)
           close(io)
           include(f)
           include(f)
       end
ERROR: LoadError: invalid redefinition of type B
Stacktrace:
 [1] top-level scope
   @ /tmp/jl_KJFFPN:2
 [2] include
   @ ./client.jl:489 [inlined]
 [3] (::var"#1#2")(f::String, io::IOStream)
   @ Main ./REPL[1]:10
 [4] mktemp(fn::var"#1#2", parent::String)
   @ Base.Filesystem ./file.jl:738
 [5] mktemp(fn::Function)
   @ Base.Filesystem ./file.jl:736
 [6] top-level scope
   @ REPL[1]:1
in expression starting at /tmp/jl_KJFFPN:2
```

but changing `a::A{<:T}` to just `a::A{T}` does not trigger that error.
